# Generated by Django 3.0.4 on 2020-05-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=20, unique=True, verbose_name='工号/学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('college', models.CharField(max_length=100, verbose_name='学院/部门')),
                ('stu_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='班级')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperture', models.FloatField(verbose_name='温度')),
                ('heat', models.BooleanField(verbose_name='发热')),
                ('sick', models.BooleanField(verbose_name='生病')),
                ('contact', models.BooleanField(verbose_name='接触过及境外人员')),
                ('overseas', models.BooleanField(verbose_name='有旅居史')),
                ('high_rish', models.BooleanField(verbose_name='在高风险地区停留过')),
                ('remarks', models.CharField(max_length=1000, null=True, verbose_name='备注')),
                ('submit_time', models.DateField(auto_now=True, verbose_name='提交时间')),
                ('father', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='survey.user')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
