# Generated by Django 3.0.4 on 2020-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200520_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='virus',
            field=models.BooleanField(default=False, verbose_name='疑似/确诊/无症状感染'),
        ),
    ]
