# Generated by Django 3.0.4 on 2020-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_question_virus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='question',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='temperture',
            field=models.FloatField(verbose_name='体温'),
        ),
    ]
